### ISSUE TITLE
code review items

### ISSUE THREAD

**Issue by kenliu** [viewthespace/pivotal-deployment-emailer#1]
General comments:
1. What is the Postgres DB used for? If we're not using it then we should deprovision the add-on
2. The Heroku dynos should be scaled to 0 because they are not used
3. There is a lot of boilerplate generated Rails code and directories that could be just deleted
4. Set up papertrail add-on so we can troubleshoot in the future

---

`delivered_pivotal_stories_mailer.rb`

line 2, line 11: move hard-coded email addresses to config

---

`delivered_stories_report.rb`

line 5: require isn't necesary, should be loaded automatically
line 18: remove hard coded API token (is this a real token? if so we should roll it over for security purposes ASAP) - best to raise an exception in case a required parameter is missing
line 31: use `inject` instead of `each`
line 32: remove hard coded list of projects
line 33, line 41: use Rails log instead of `puts` (and throughout rest of code)

**Comment by newOnahtaN** [comment]
Note on line 18: It's not a real token - its a dummy token I set up for testing purposes. The beginning of that function checks to see if it has an environment variable to reference for a token, and if it doesn't it uses this dummy token.

**Comment by kbaum** [comment]
Right.. but you don't want to hide a configuration missing.. you kind of want to shout "Hey you're missing XYZ environment variable!"

**Comment by kbaum** [comment]
One use case we need to consider.. this is really for our web application only.  We don't want to include mobile pivotal projects within this.

**Comment by newOnahtaN** [comment]
@kbaum We're actually not including mobile projects - that logic is currently in `delivered_stories_report.rb`, but I used hard-coded names of our mobile projects, I'm going to change how I've done that, but for now that's actually been considered.

And thanks for the tip on throwing an error!

**Comment by kbaum** [comment]
Ok cool!

**Comment by kbaum** [comment]
I also commented a bunch on a commit.. not sure if you got it or not.  I wonder if we should put this code on a branch.. have master be empty and then do a pull request to master.

**Comment by newOnahtaN** [comment]
Yup, I got all those comments - I'll branch out from here with my fixes for these problems. Thanks guys!! Definitely some ruby-esque things that I need to learn - I appreciate the comments :)

**Comment by kbaum** [comment]
Thank you!  Great work!
